[pytest]
testpaths = web/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
asyncio_mode = auto
# Désactive les warnings de deprecation non pertinents
filterwarnings =
    ignore::DeprecationWarning:passlib
    ignore::DeprecationWarning:jose
